version: "3.7"
services:
  svtplay-dl:
    build:
      context: .
    image: svtplay-dl
    restart: always
    user: "500:500"
    volumes:
      - ./out:/output
    environment:
      SVTPLAY_DL_EPISODE_URLS: >
         https://www.svtplay.se/video/22581746/funkiskungen
      SVTPLAY_DL_PLEX_TOKEN: <your plex token>
      SVTPLAY_DL_PLEX_URL: servern.local
      SVTPLAY_DL_PLEX_LIBRARY_SECTION: 5
