services:
  # https://svtplay-dl.se/options/
  svtplay-dl:
    build:
      context: .
      dockerfile: Dockerfile
    image: svtplay-dl:latest
    container_name: svtplay-dl
    restart: unless-stopped
    environment:
      SVTPLAY_DL_COMMANDS: |
        svtplay-dl --all-last 1 --subfolder  -o /downloads https://www.svtplay.se/video/KVk3L5d/dips
      OUTPUT_DIR: /downloads
    volumes:
      - ./downloads:/downloads
