services:
  # https://svtplay-dl.se/options/
  svtplay-dl:
    build:
      context: .
      dockerfile: Dockerfile
    image: svtplay-dl:latest
    container_name: svtplay-dl
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/downloads
