services:
  # https://svtplay-dl.se/options/
  svtplay-dl:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: docker-svtplay-dl:latest
    container_name: docker-svtplay-dl
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: '* * * * *'
      SVTPLAY_DL_COMMANDS: |
        svtplay-dl --all-last 1 --subfolder  -o /downloads https://www.svtplay.se/video/KVk3L5d/dips
        svtplay-dl --all-last 1 --subfolder  -o /downloads https://www.svtplay.se/video/ja4YNRY/sune-vs-sune
      OUTPUT_DIR: /downloads
    volumes:
      - ./downloads:/downloads
      - ./config:/config:ro
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
